# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_review_information(
  first_name: "Jacob",
  last_name: "Prickett",
  phone_number: "5869965253",
  email_address: "jprickett821@gmail.com",
)

submission_information({    
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})

app_rating_config_path './fastlane/rating_config.json'

automatic_release false

app_icon './fastlane/metadata/app_icon.jpg'