# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :test_flight do

    build

    resign_ipa

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

    upload_to_testflight(
      ipa: "./build/Calculator.ipa", 
      changelog: "Add Shake Gesture to clear stored information",
      distribute_external: true,
      notify_external_testers: true,
      testers_file_path: "./testers/ford_testers_export.csv",
      groups: ["Ford Testers"],
      reject_build_waiting_for_review: true
    )
  end

  desc "Submit to the AppStore"
  lane :app_store do |options|
    
    build

    resign_ipa

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

    upload_to_app_store(
      username: "jprickett821@gmail.com",
      app_version: options[:version_number],
      metadata_path: "./fastlane/metadata",
      screenshots_path: "./fastlane/screenshots",
      phased_release: false,
      force: true
    )
  end

  desc "Submit latest TF Build to AppStore"
  lane :submit_latest_build do
    sh("cd .. ; fastlane deliver submit_build --force --build-number latest")
  end

  # Helper Stuff

  desc "Build App with Development Profile/Cert"
  lane :build do
    gym(
      scheme: "Calculator",
      export_method: "app-store",
      build_path: "./build",
      output_directory: "./build",
      buildlog_path: "tmp",
      xcargs: "-verbose"
    )
  end

  desc "Resign App with Distribution Profile/Cert"
  lane :resign_ipa do
    sigh(
      output_path: "./profiles"
    )
    resign(
      ipa: "./build/Calculator.ipa", 
      signing_identity: "iPhone Distribution: Jacob Prickett (24DLJQTAR9)"
    )
  end

end
